[[SampleSetConfigs.set1]]
fileNames = [
	"assets/samples/loops/soundset_1/drumloop.aiff",
	"assets/samples/loops/soundset_1/moog.aiff",
	"assets/samples/loops/soundset_1/horns.aiff",
]

[[SampleSetConfigs.set2]]
fileNames = [
	"assets/samples/loops/soundset_2/kick.aiff",
	"assets/samples/loops/soundset_2/snare.aiff",
	"assets/samples/loops/soundset_2/hihats.aiff",
	"assets/samples/loops/soundset_2/fx.aiff",
]

[[SampleSetConfigs.set3]]
fileNames = [
	"assets/samples/loops/soundset_3/kick.aiff",
	"assets/samples/loops/soundset_3/snare.aiff",
	"assets/samples/loops/soundset_3/hihats.aiff",
	"assets/samples/loops/soundset_3/maracas.aiff",
	"assets/samples/loops/soundset_3/housechords.aiff",
	"assets/samples/loops/soundset_3/bass.aiff",
]

[GPIOConfigs]
18 = "nextsoundset"
23 = "prevsoundset"
12 = "toggle_0"
16 = "toggle_1"
21 = "toggle_2"
24 = "toggle_3"
25 = "toggle_4"
20 = "toggle_5"
4 = "toggle_6"
17 = "toggle_7"
27 = "toggle_8"
22 = "toggle_9"
6 = "begin"
