[[SampleSetConfigs.set1]]
fileNames = [
	"assets/samples/loops/soundset_1/claps.aiff",
	"assets/samples/loops/soundset_1/fx.aiff",
	"assets/samples/loops/soundset_1/hightom.aiff",
	"assets/samples/loops/soundset_1/hihats.aiff",
	"assets/samples/loops/soundset_1/kick.aiff",
	"assets/samples/loops/soundset_1/lowtom.aiff",
	"assets/samples/loops/soundset_1/midtom.aiff",
	"assets/samples/loops/soundset_1/ride.aiff",
	"assets/samples/loops/soundset_1/rimshot.aiff",
	"assets/samples/loops/soundset_1/shaker.aiff",
]

[[SampleSetConfigs.set2]]
fileNames = [
	"assets/samples/loops/soundset_2/kick.aiff",
	"assets/samples/loops/soundset_2/snare.aiff",
	"assets/samples/loops/soundset_2/hihats.aiff",
	"assets/samples/loops/soundset_2/fx.aiff",
	"assets/samples/loops/soundset_2/303.aiff",
	"assets/samples/loops/soundset_2/bleep1.aiff",
	"assets/samples/loops/soundset_2/bleep2.aiff",
	"assets/samples/loops/soundset_2/bleep3.aiff",
	"assets/samples/loops/soundset_2/bleep4.aiff",
	"assets/samples/loops/soundset_2/bleep5.aiff",
]

[[SampleSetConfigs.set3]]
fileNames = [
	"assets/samples/loops/soundset_3/kick.aiff",
	"assets/samples/loops/soundset_3/snare.aiff",
	"assets/samples/loops/soundset_3/hihats.aiff",
	"assets/samples/loops/soundset_3/maracas.aiff",
	"assets/samples/loops/soundset_3/housechords.aiff",
	"assets/samples/loops/soundset_3/bass.aiff",
	"assets/samples/loops/soundset_3/conga1.aiff",
	"assets/samples/loops/soundset_3/conga2.aiff",
	"assets/samples/loops/soundset_3/conga3.aiff",
	"assets/samples/loops/soundset_3/crash.aiff",
]

[GPIOConfigs]
18 = "nextsoundset"
23 = "prevsoundset"
12 = "toggle_0"
16 = "toggle_1"
21 = "toggle_2"
24 = "toggle_3"
25 = "toggle_4"
20 = "toggle_5"
4 = "toggle_6"
17 = "toggle_7"
27 = "toggle_8"
22 = "toggle_9"
6 = "begin"
